# Generated by Django 4.2.6 on 2024-04-02 22:21

from django.db import migrations
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_user_id'),
    ]
