# Generated by Django 4.2.6 on 2024-04-02 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_bid_counter_user_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
