# Generated by Django 4.2.6 on 2024-04-03 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
    ]
