# Generated by Django 4.2.6 on 2024-04-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_listings',
            fields=[
                ('uniqueid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('startingbid', models.IntegerField()),
                ('currentprice', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('imageurl', models.CharField(max_length=255)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('bid_counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist_counter',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
        migrations.AddField(
            model_name='all_listings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
