# Generated by Django 4.2.6 on 2024-04-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_all_listings_id_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_listings',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='commerce/auctions/static/auctions/'),
        ),
    ]
