# Generated by Django 4.2.6 on 2024-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_all_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='all_listings',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
